# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3c1a96d30832bb80c84d5b87aa689f09a09ae5261033ba2c1718a84259fe020f082dd0e768e5fe865c69fb140ebe44b2749dc30c3218d7ebf342240feb83cf7d

test:
  secret_key_base: 75c879067024fe742f36617a6fca4221c95a2c5f1023cd7d46b2ff05d88322a2031a0c3f292306afa3580d2d803199906d85b8207a43aaa3791bbce653e7f631

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
